# 테스트 서버
@baseUrl = http://test.manager.ok114.kr

###
#전화번호가 DB에 존재하는지 체크하는 API
#요청 데이터
#count:  요청 전화번호 갯수 [ 현재는 의미 없으나 추후 사용 가능성 있음 ]
#phonNumber: 요청 전화번호 목록
POST {{baseUrl}}/api/bizData/exists HTTP/1.1
Content-Type: application/json

{
    "count": 100,
    "phoneNumber": [
        "0415640001",
        "1111111111",
        "0415795552",
        "0415743775",
        "0000000000"
    ]
}